feat: add groupBySchema to group types and enums under a namespace
valtyr/prisma-kysely pull request #110
Opened 2024-10-11 19:36 UTC by arthurfiorette

- code
- tests
- docs

2025-01-10 18:41 UTC, arthurfiorette commented
I've published this PR as `@arthurfiorette/prisma-kysely@1.9.0` if anyone wants it

2025-02-04 03:34 UTC, Bathlamos commented
I tried your implementation on a schema with a hundred tables and it works fine. ESLint complains about the use of namespaces, which aren't necessary anyway as Prisma already forces the model names to be distinct even if they are in different schemas. Another interesting avenue of improvement might be to designate a schema as default, e.g. the `public` schema, to avoid prefixing its models.

2025-03-05 19:47 UTC, arthurfiorette commented
Hey @Bathlamos, I just added a `defaultSchema` option!

2025-05-17 14:59 UTC, igalklebanov commented
Hey 👋 

I think that the use of `namespaces` should be replaced with a file (module) per PostgreSQL schema.
If people still want that namespace syntax when consuming, they can just:

```ts
import * as Public from 'path/to/public/schema/types'

Public.Person
```

More shorter files = better performance as seen with https://www.prisma.io/docs/orm/prisma-schema/overview/generators#output-splitting-and-importing-types.

2025-05-17 16:13 UTC, arthurfiorette commented
In general, `* as Public` and other forms of non-named exports don't work well with IntelliSense or auto-imports, unless we manually emit both JS and DTS files using the `export as namespace` syntax. However, doing so would significantly deviate from the current plugin architecture.

Also, the output generated by `prisma-kysely` differs from Prisma in that Prisma emits a large number of complex type definitions per model. In contrast, `prisma-kysely` provides a straightforward 1:1 mapping. So unless we're dealing with thousands of database models, performance shouldn't be a concern here.

Namespaces are often considered problematic when declared across multiple files, as that can make it harder for the TypeScript type checker to do its job efficiently. However, that doesn't seem to be the case here also.

Given all of the above, I still believe using namespaces is the right approach here.

2025-05-17 18:52 UTC, arthurfiorette commented
Hey @igalklebanov!

> the team recommending https://github.com/microsoft/TypeScript/issues/30994#issuecomment-492017219

As far as I understood, that comment points out problems that happens when using namespaces across multiple files. _(As the typescript team suffered that personally since TS's own codebase was structured as a few giant namespaces)_

It was easy to implement namespaces here because of our current architecture as we can simply reuse everything already made and wrap the result with an `ts.factory.createModuleDeclaration()`. 

It also said:

- "If you have code that you feel needs to use a namespace, **_more power to you and go for it_**, but most of the time you don't need one, as we now have a different conceptual organizational model recommended for **_large-scale JS (modules)_**"

> eslint yelling at people in [the recommended ruleset](https://typescript-eslint.io/rules/no-namespace/)

We have eslint rules to disallow/enforce almost everything. Ideally, generated files should not be linted. Is there something more personal than linting rules?

> This is a DX problem.

DX usually means a combination of personal preference and familiarity.

> So either provide both.

I'd love to later help you by reviewing a PR adding support your alternative :)

> Another reason to avoid them?

The problem said states something that does not happens in this use-case: 1 single file with 1 model per file.

---

I'll never be against new features but personal preferences does not seems a compelling use case since the current implementation does not seems worse ihmo.

Although using `import * as Group` and emitting multiple files would require an interesting rewrite of `generateFile.ts` and all the known problems when correctly generating import statements across multiple files for many cjs/esm tsconfig variants.

As far as my knowledge goes into the type checker and compiler internals, enabling `isolatedModules` makes namespace declarations type-checking behavior almost identical as if types were declared in the file root _(Although I might be wrong here)_.

2025-05-17 19:57 UTC, igalklebanov commented
> As far as I understood, that comment points out problems that happens when using namespaces across multiple files. (As the typescript team suffered that personally since TS's own codebase was structured as a few giant namespaces)

> It also said:
> 
> "If you have code that you feel needs to use a namespace, more power to you and go for it, but most of the time you don't need one, as we now have a different conceptual organizational model recommended for large-scale JS (modules)" 

This is not about namespaces, but the public perception of them, prominent tooling recommending against their usage, and the majority of TypeScript developers not wanting them in their codebases as a result.

Forcing them, by surprise, as the only way, is not good DX, and is fighting against the grain.

No amount of cherry-picking is going to help the case for them.

> We have eslint rules to disallow/enforce almost everything.

But this one is in the recommended preset of a linter that's downloaded 48,854,801 times per week. How many people care enough (about namespaces) to tinker with the recommended preset and allow them?

> Ideally, generated files should not be linted. Is there something more personal than linting rules?

How many people configure their tooling properly? How many headaches will this cause?

> I'd love to later help you by reviewing a PR adding support your alternative :)

I didn't mean to demand anything. This is just how I talk sometimes. :)

2025-05-19 02:50 UTC, alii commented
I think namespaces are suitable here

Ultimately I believe it's unfortunate that no-namespaces was a default/recommended rule for the TypeScript eslint plugin. I personally usually turn that one off.

Additionally namespaces are a pretty similar representation in TypeScript of what it means to have a database schema. While separate files do represent some separation to some degree, I would say namespaces are a closer match in terms of what they semantically represent.

Could the solution be that we have a `// eslint-disable` comment at the top of file? It sounds like the only issue with using namespaces is that people using ESLint will see errors in the file.

2025-05-19 03:00 UTC, alii commented on src/utils/camelCase.ts
Maybe rename from camelCase.ts to `words.ts` or `casing.ts` or `letters.ts` or something similar

2025-05-19 03:09 UTC, alii requested changes
The changes seem reasonable to me and test coverage makes sense.

Just a couple of nits I've left a comment on.

Separately I've left a PR on your fork @arthurfiorette - https://github.com/arthurfiorette/prisma-kysely/pull/1 which I think we could merge before _this_ PR merges, as part of the current effort to bring prisma-kysely back to life.

2025-05-19 03:48 UTC, arthurfiorette commented on src/utils/validateConfig.ts
> +    filterBySchema: z.array(z.string()).optional(),
I did change the readme.

![image](https://github.com/user-attachments/assets/e0e980d0-de61-42aa-864a-a67897c773af)

2025-05-19 10:29 UTC, igalklebanov commented
> I think namespaces are suitable here
> 
> In my opinion I believe it's unfortunate that no-namespaces was a default/recommended rule for the TypeScript eslint plugin. I personally usually turn that one off.
> 
> Additionally namespaces are a pretty similar representation in TypeScript of what it means to have a database schema. While separate files do represent some separation to some degree, I would say namespaces are a closer match in terms of what they semantically represent.

Similar to what I replied to @arthurfiorette, namespaces are not the issue here. It's the negative public perception, following what was said and done about them for years. What's done is done.

> Could the solution be that we have a `// eslint-disable` comment at the top of file? It sounds like the only issue with using namespaces is that people using ESLint will see errors in the file.

You'd also need to provide a disable comment for `biome`, just in case some people explicitly enable `lint/style/noNamespace`.

It wouldn't solve it for people who configure [noInlineConfig](https://eslint.org/docs/latest/use/configure/rules#disabling-inline-comments).

But linters are not the only issue. Negative public perception of namespaces means people might not like `prisma-kysely` shoving unwanted syntax in their codebase, without providing alternatives. Imagine Colin forcing people to use TypeScript string enums (which he likes btw) in Zod v4 as the only way for users to achieve a certain goal.

2025-05-20 18:54 UTC, valtyr commented
I don't have a particularily strong opinion for or against namespaces as long as we're not breaking any behavior people are used to from the library.

In regards to the linting issue: this could be solved with an option to prepend text to the generated file. I feel like that's the solution I expect from codegen libraries. That way people can add ignore comments for the tools that they use, and we won't have to assume anything.

2025-06-22 19:27 UTC, alii commented on src/helpers/multiSchemaHelpers.test.ts
> +  const result = convertToMultiSchemaModels(
nitpick: `convertToMultiSchemaModels` could also accept an options object as it's again hard to quickly scan what the arguments here are
```suggestion
  const result = convertToMultiSchemaModels(
```

2025-06-22 19:27 UTC, alii commented on src/helpers/generateModel.test.ts
> +    "public"
Nitpick: generateModel should/could accept an options object instead here. The new arguments here are hard to immediately understand when scanning usages of this function.
```suggestion
      groupBySchema: false,
      defaultSchema: "public",
      dbTypeName: "DB",
    },
    false,
    "public"
```

2025-06-22 20:17 UTC, alii commented on src/helpers/generateEnumType.ts
> +    return undefined;
Is it more-correct to throw in this case? Or a better question to ask is "do we ned make sure an error is surfaced to the user here?"

I ask because there's code that uses generateEnumType (which can return undedfined) that does a check for `!!value` instead of potentially showing a warning/erroring

2025-06-22 20:33 UTC, arthurfiorette commented
Hey @frannyfx, just letting you know that I copied your #100 PR into this one so we can avoid merge conflicts and ship your fix as fast as possible.

2025-06-23 07:54 UTC, alii commented on src/helpers/generateEnumType.ts
> +    return undefined;
The fact that `generateStringLiteralUnion` *could* return null means we should just surface the error in the case we do reach that condition, for whatever possible reason.  I think it's fine to just throw here

2025-06-23 13:46 UTC, arthurfiorette commented on src/helpers/generateEnumType.ts
> +    return undefined;
Why break their entire schema generation when we can just skip the empty enum?

2025-08-31 06:45 UTC, alii commented
/snapshot

2025-08-31 07:03 UTC, alii commented
Let's get this merged. Thank you very much @arthurfiorette for all your efforts working on these changes ❤️

2025-08-31 07:04 UTC, merged